Repository NVlabs/FPSci, pull requests merged in 2020-06, with the labels that each got.

#140 MenuConfig as reference instead of copy in UserMenu
  source/GuiElements.h
Labels: bug, invalid

#139 Documentation fixes
  docs/experimentConfigReadme.md
  docs/general_config.md
  docs/getting_started.md
  docs/startupConfigReadme.md
  docs/systemConfigReadme.md
  docs/userConfigReadme.md
  docs/userStatusReadme.md
  docs/weaponConfigReadme.md
Labels: enhancement, invalid

#156 Error printing/displaying user (and other) info on first run
  source/ConfigFiles.h
  source/GuiElements.cpp
Labels: bug

#155 FPSci packager generator
  .gitignore
  scripts/package/fpsci_packager.py
Labels: enhancement

#153 Automatic session progression
  docs/general_config.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
Labels: enhancement

#149 Blocks within sessions
  docs/experimentConfigReadme.md
  source/ConfigFiles.h
  source/Logger.cpp
  source/Session.cpp
  source/Session.h
Labels: enhancement

#150 Project reorganization
  FirstPersonScience.sln
  FirstPersonScience.vcxproj
  FirstPersonScience.vcxproj.filters
Labels: enhancement

#159 Center the question dialog(s) on top of user menu
  source/FPSciApp.cpp
  source/FPSciApp.h
Labels: enhancement

#162 Update user config on user change in application
  source/ConfigFiles.h
  source/GuiElements.cpp
Labels: invalid

#169 Add automatic closing of app on experiment/session end
  docs/experimentConfigReadme.md
  source/ConfigFiles.h
  source/Session.cpp
Labels: enhancement

#118 Split Player Camera from Debug Camera and Restore G3D Scene Editor Functionality
  .gitignore
  docs/scene.md
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  source/TargetEntity.cpp
  source/Weapon.cpp
  tests/FPSciTests.cpp
Labels: enhancement

#168 Experiment designer control of whether to show reference target
  docs/general_config.md
  source/ConfigFiles.h
  source/Session.cpp
  source/Session.h
Labels: enhancement

#180 Only serialize non-default session-specific config parameters
  source/ConfigFiles.h
Labels: enhancement

#173 Move currentUser from user config to user status
  data-files/test/userstatus.Any
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/GuiElements.cpp
  source/GuiElements.h
  source/Session.cpp
  tests/FPSciTests.cpp
Labels: enhancement, invalid

#183 Add requirement for click in addition to scoreboardDuration parameter
  docs/general_config.md
  source/ConfigFiles.h
  source/Session.cpp
Labels: enhancement
