Repository NVlabs/FPSci, pull requests merged in 2020-07, with the labels that each got.

#184 Custom feedback
  docs/general_config.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/Session.cpp
  source/Session.h
Labels: enhancement

#189 Doc fixes
  docs/developermode.md
  docs/experimentConfigReadme.md
  docs/general_config.md
  docs/getting_started.md
  docs/keymap.md
  docs/patheditor.md
  docs/readme.md
  docs/userConfigReadme.md
Labels: bug

#193 Quick fix for showExperimentSettings = false
  source/GuiElements.cpp
Labels: bug

#198 Updated sample startup config docs
  docs/startupConfigReadme.md
Labels: bug

#200 Per trial feedback unconditional of session description
  source/Session.cpp
Labels: invalid

#199 Target previews
  docs/general_config.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/Session.cpp
  source/Session.h
  source/TargetEntity.h
  tests/FPSciTests.cpp
Labels: enhancement

#196 Add support for all config paths in startup config
  data-files/test/startupconfig.Any
  docs/startupConfigReadme.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
Labels: enhancement

#206 Prevents crash with no valid sessions
  source/GuiElements.cpp
  source/Session.cpp
Labels: bug

#203 Refactor system/latency logger config
  FPSci.lib.vcxproj.filters
  docs/general_config.md
  docs/startupConfigReadme.md
  docs/systemConfigReadme.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  source/Session.h
Labels: enhancement, idea

#201 Remove the old sample configs
  data-files/readme.md
  docs/SAMPLE configs/SAMPLEexperimentconfig.Any
  docs/SAMPLE configs/SAMPLEsystemconfig.Any
  docs/SAMPLE configs/SAMPLEuserconfig.Any
  docs/SAMPLE configs/SAMPLEuserstatus.Any
Labels: bug

#207 Rename duration parameters and states
  data-files/test/experimentconfig.Any
  data-files/test/keymap.Any
  data-files/test/startupconfig.Any
  data-files/test/systemconfig.Any
  docs/general_config.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  tests/FPSciTests.cpp
Labels: enhancement

#209 Restore user menu slider and checkbox interaction
  source/GuiElements.cpp
  source/GuiElements.h
Labels: bug

#186 Get tests running successfully
  FPSci.test.vcxproj
  FPSci.test.vcxproj.filters
  data-files/test/experimentconfig.Any
  source/Weapon.h
  tests/FPSciTests.cpp
  tests/FPSciTests.h
  tests/TestFakeInput.cpp
Labels: bug

#210 Create a vs directory for all Visual Studio exclusive files
  data-files/icon.ico
  resources.rc
  scripts/package/fpsci_packager.sh
  scripts/package/fpsci_packager_generator.py
  vs/FPSci.lib.vcxproj
  vs/FPSci.lib.vcxproj.filters
  vs/FPSci.lib.vcxproj.user
  vs/FPSci.test.vcxproj
  vs/FPSci.test.vcxproj.filters
  vs/FPSci.test.vcxproj.user
  vs/FirstPersonScience.sln
  vs/FirstPersonScience.vcxproj
  vs/FirstPersonScience.vcxproj.filters
  vs/FirstPersonScience.vcxproj.user
  vs/packages.config
  vs/resources.rc
Labels: enhancement

#213 Test `packages` path in `vs`
  .gitignore
  vs/FPSci.test.vcxproj
Labels: bug

#216 Fixes for some unexpected log behavior
  source/FPSciApp.cpp
  source/Logger.cpp
Labels: bug

#217 Allow packager generator to work without `log.txt`
  scripts/package/fpsci_packager.sh
  scripts/package/fpsci_packager_generator.py
Labels: enhancement

#220 Generate batch packager script
  .gitignore
  scripts/package/fpsci_packager.sh
  scripts/package/fpsci_packager_generator.py
Labels: enhancement

#221 Cooldown reset
  source/ConfigFiles.h
  source/Session.cpp
Labels: enhancement

#219 Split/reuse updateTargetColor() for preview targets
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  source/TargetEntity.h
Labels: bug, enhancement

#222 Extend model scaling range w/ scale factor
  data-files/test/experimentconfig.Any
  data-files/test/userstatus.Any
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  source/Session.h
  source/TargetEntity.h
  source/WaypointManager.cpp
  tests/FPSciTests.cpp
  tests/FPSciTests.h
Labels: enhancement

#176 Scene configuration
  data-files/test/experimentconfig.Any
  docs/general_config.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/PhysicsScene.h
  source/PlayerEntity.h
Labels: enhancement

#225 Allow developers to reload their configs from disk while running
  docs/developermode.md
  docs/keymap.md
  source/ConfigFiles.h
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/GuiElements.h
Labels: enhancement

#224 Adds command line arguments for packager generator
  scripts/package/fpsci_packager.sh
  scripts/package/fpsci_packager_generator.py
Labels: enhancement

#228 dbFilename command substring support
  docs/general_config.md
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
  source/Session.h
Labels: enhancement

#223 Lower audio latency (requires G3D r7012 or newer)
  source/main.cpp
  tests/main.cpp
Labels: enhancement
