Repository NVlabs/FPSci, pull requests merged in 2021-09, with the labels that each got.

#312 Add samples to the packager list in the script
  scripts/package/fpsci_packager.sh
Labels: bug

#323 Add `showReferenceTargetMissDecals` parameter
  docs/general_config.md
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Session.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#322 Add `clearMissDecalsWithReference` parameter
  docs/general_config.md
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Session.cpp
Labels: enhancement

#324 Turn off sounds for test experiment
  data-files/test/experimentconfig.Any
Labels: enhancement

#327 Rendering pipeline documentation
  docs/content/fpsci-pipeline.png
  docs/general_config.md
Labels: bug, enhancement

#319 Support for programmable variable frame rate
  docs/AnyFile.md
  docs/general_config.md
  source/FPSciApp.cpp
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Session.cpp
  source/Session.h
Labels: enhancement

#316 Update Any output to be JSON compatible
  docs/startupConfigReadme.md
  source/ExperimentConfig.cpp
  source/ExperimentConfig.h
  source/FPSciApp.cpp
  source/KeyMapping.cpp
  source/KeyMapping.h
  source/StartupConfig.cpp
  source/StartupConfig.h
  source/SystemConfig.cpp
  source/SystemConfig.h
  source/UserConfig.cpp
  source/UserConfig.h
  source/UserStatus.cpp
  source/UserStatus.h
  source/WaypointManager.cpp
  source/WaypointManager.h
Labels: enhancement

#314 Improve Banner
  docs/content/annotated_banner.png
  docs/general_config.md
  source/FPSciGraphics.cpp
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Session.cpp
  source/Session.h
Labels: enhancement

#321 Add `referenceTargetHitSound` to audio config
  docs/general_config.md
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/FpsConfig.cpp
  source/FpsConfig.h
Labels: enhancement

#328 Use waypointManager null check instead of `waypointEditorMode` parameter
  source/FPSciApp.cpp
  source/FPSciGraphics.cpp
  source/TargetEntity.h
  source/WaypointManager.cpp
  source/WaypointManager.h
Labels: bug
