Repository NVlabs/FPSci, pull requests merged in 2021-04, with the labels that each got.

#300 Cache session shaders manually to work around LAUNCH_SHADER assumption
  source/FPSciApp.cpp
  source/FPSciApp.h
Labels: bug

#301 Disable crouch/jump as default (if unspecified)
  docs/general_config.md
  source/FpsConfig.h
Labels: enhancement

#302 Add support for question response order randomization
  docs/general_config.md
  source/FPSciApp.cpp
  source/FpsConfig.cpp
  source/FpsConfig.h
Labels: enhancement

#298 Fix for spawning destination targets at their first destination
  source/Session.cpp
Labels: enhancement, invalid

#303 Changes for a redesigned graphics pipeline
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/FPSciGraphics.cpp
  vs/FPSci.lib.vcxproj
  vs/FPSci.lib.vcxproj.filters
Labels: enhancement

#299 Added symmetric eccentricity support to player space target spawn positions
  docs/experimentConfigReadme.md
  source/Logger.cpp
  source/Session.cpp
  source/TargetEntity.cpp
  source/TargetEntity.h
Labels: enhancement

#305 Fix spawn bounds AABox to remove debug error
  data-files/test/experimentconfig.Any
Labels: bug

#122 Update for split 2D buffer/shaders
  docs/general_config.md
  source/ExperimentConfig.cpp
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/FPSciGraphics.cpp
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Session.cpp
  source/Session.h
  vs/FPSci.lib.vcxproj
  vs/FPSci.lib.vcxproj.filters
Labels: enhancement
