Repository NVlabs/FPSci, pull requests merged in 2023-01, with the labels that each got.

#406 Set guard band to 0
  source/FPSciApp.cpp
Labels: bug

#408 Fix for crash on load w/ experiment complete
  source/FPSciApp.cpp
Labels: bug

#404 Fixes for reticle preview and `allowReticleChange`
  docs/general_config.md
  source/FPSciApp.cpp
  source/GuiElements.cpp
  source/UserConfig.h
Labels: bug, enhancement

#409 Update packager FMOD dll (G3D r7202)
  scripts/package/fpsci_packager.sh
Labels: bug

#410 Session progress fix
  source/FPSciApp.cpp
  source/FPSciApp.h
  source/Session.cpp
Labels: bug

#396 Task flow integration
  data-files/samples/tasks.Experiment.Any
  data-files/samples/tasks.Status.Any
  data-files/samples/twoifc-task.Experiment.Any
  data-files/samples/twoifc-task.Status.Any
  data-files/samples/twoifc-trial.Experiment.Any
  data-files/samples/twoifc-trial.Status.Any
  data-files/samples/twoifc.Status.Any
  docs/experimentConfigReadme.md
  docs/general_config.md
  scripts/package/fpsci_packager.sh
  source/FPSciApp.h
  source/FpsConfig.cpp
  source/FpsConfig.h
  source/Logger.cpp
  source/Logger.h
  source/Session.cpp
  source/Session.h
  tests/FPSciTests.cpp
Labels: enhancement

#411 Don't modify widget manager prior to reinit
  source/FPSciApp.cpp
Labels: bug

#414 Don't load weapon sounds if audio disabled
  source/FPSciApp.cpp
Labels: bug
